name: bell_delivery_hub
description: null

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ai_barcode: ^1.1.4
  android_intent: ^0.3.7+6
  cached_network_image: ^2.3.3
  clippy_flutter: ^1.1.1
  connectivity: ^2.0.2
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  dio: ^3.0.10
  dio_flutter_transformer: ^3.0.2
  encrypt: ^4.1.0
  equatable: ^1.2.5
  firebase_core: ^0.5.3
  flash: ^1.3.1
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.0
  flutter_local_notifications: ^3.0.3
  flutter_screenutil: ^3.2.0
  flutter_vector_icons: ^0.2.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.3
  hive: ^1.4.4+1
  intl: ^0.16.1
  json_serializable: ^3.5.0
  modal_bottom_sheet: ^1.0.0+1
  package_info: ^0.4.3+2
  permission_handler: ^5.0.1+1
  pretty_dio_logger: ^1.1.1
  retrofit: ^1.3.4+1
  shared_preferences: ^0.5.12+2
  shimmer: ^1.1.2
  timeago: ^2.0.28
  url_launcher: ^5.7.10
  websafe_svg: ^1.1.4
  qr_code_scanner: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9
  freezed: ^0.12.2
  hive_generator: ^0.8.1
  retrofit_generator: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf

    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
